### ISSUE TITLE
Showing source code instead of the Card

### ISSUE THREAD

**Issue by NoahDragon** [Gisonrg/hexo-github-card#3]
Thanks for the awesome plugin.

Recently seems like it malfunctioning. The card could display but show HTML codes.

![image](https://user-images.githubusercontent.com/5704064/27893575-81b0be36-61d4-11e7-8a93-c60c302dc88a.png)

Not sure if this is something related to Github.

**Comment by Gisonrg** [comment]
Hi,
Thanks for pointing out. It should be fixed by now. This is due to an issue of jsdelivr for serving the lib files.
